// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.3

package test

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type TestHTTPServer interface {
	TestSnowflake(context.Context, *TestSnowflakeRequest) (*TestSnowflakeReply, error)
}

func RegisterTestHTTPServer(s *http.Server, srv TestHTTPServer) {
	r := s.Route("/")
	r.GET("/snowflake", _Test_TestSnowflake0_HTTP_Handler(srv))
}

func _Test_TestSnowflake0_HTTP_Handler(srv TestHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TestSnowflakeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.test.Test/TestSnowflake")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TestSnowflake(ctx, req.(*TestSnowflakeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TestSnowflakeReply)
		return ctx.Result(200, reply)
	}
}

type TestHTTPClient interface {
	TestSnowflake(ctx context.Context, req *TestSnowflakeRequest, opts ...http.CallOption) (rsp *TestSnowflakeReply, err error)
}

type TestHTTPClientImpl struct {
	cc *http.Client
}

func NewTestHTTPClient(client *http.Client) TestHTTPClient {
	return &TestHTTPClientImpl{client}
}

func (c *TestHTTPClientImpl) TestSnowflake(ctx context.Context, in *TestSnowflakeRequest, opts ...http.CallOption) (*TestSnowflakeReply, error) {
	var out TestSnowflakeReply
	pattern := "/snowflake"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.test.Test/TestSnowflake"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
