// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/test/test.proto

package test

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestSnowflakeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataCenterId int64 `protobuf:"varint,1,opt,name=dataCenterId,proto3" json:"dataCenterId,omitempty"`
	WorkerId     int64 `protobuf:"varint,2,opt,name=workerId,proto3" json:"workerId,omitempty"`
}

func (x *TestSnowflakeRequest) Reset() {
	*x = TestSnowflakeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_test_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSnowflakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSnowflakeRequest) ProtoMessage() {}

func (x *TestSnowflakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_test_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSnowflakeRequest.ProtoReflect.Descriptor instead.
func (*TestSnowflakeRequest) Descriptor() ([]byte, []int) {
	return file_api_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestSnowflakeRequest) GetDataCenterId() int64 {
	if x != nil {
		return x.DataCenterId
	}
	return 0
}

func (x *TestSnowflakeRequest) GetWorkerId() int64 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

type TestSnowflakeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnowFlakeId int64 `protobuf:"varint,1,opt,name=snowFlakeId,proto3" json:"snowFlakeId,omitempty"`
}

func (x *TestSnowflakeReply) Reset() {
	*x = TestSnowflakeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_test_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSnowflakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSnowflakeReply) ProtoMessage() {}

func (x *TestSnowflakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_test_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSnowflakeReply.ProtoReflect.Descriptor instead.
func (*TestSnowflakeReply) Descriptor() ([]byte, []int) {
	return file_api_test_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestSnowflakeReply) GetSnowFlakeId() int64 {
	if x != nil {
		return x.SnowFlakeId
	}
	return 0
}

var File_api_test_test_proto protoreflect.FileDescriptor

var file_api_test_test_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a,
	0x14, 0x54, 0x65, 0x73, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x61, 0x74,
	0x61, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x12, 0x54, 0x65, 0x73, 0x74, 0x53, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x6e, 0x6f, 0x77, 0x46, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x73, 0x6e, 0x6f, 0x77, 0x46, 0x6c, 0x61, 0x6b, 0x65, 0x49, 0x64, 0x32, 0x69, 0x0a,
	0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x61, 0x0a, 0x0d, 0x54, 0x65, 0x73, 0x74, 0x53, 0x6e, 0x6f,
	0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x73,
	0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x42, 0x23, 0x0a, 0x08, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x50, 0x01, 0x5a, 0x15, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_test_test_proto_rawDescOnce sync.Once
	file_api_test_test_proto_rawDescData = file_api_test_test_proto_rawDesc
)

func file_api_test_test_proto_rawDescGZIP() []byte {
	file_api_test_test_proto_rawDescOnce.Do(func() {
		file_api_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_test_test_proto_rawDescData)
	})
	return file_api_test_test_proto_rawDescData
}

var file_api_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_test_test_proto_goTypes = []interface{}{
	(*TestSnowflakeRequest)(nil), // 0: api.test.TestSnowflakeRequest
	(*TestSnowflakeReply)(nil),   // 1: api.test.TestSnowflakeReply
}
var file_api_test_test_proto_depIdxs = []int32{
	0, // 0: api.test.Test.TestSnowflake:input_type -> api.test.TestSnowflakeRequest
	1, // 1: api.test.Test.TestSnowflake:output_type -> api.test.TestSnowflakeReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_test_test_proto_init() }
func file_api_test_test_proto_init() {
	if File_api_test_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_test_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSnowflakeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_test_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSnowflakeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_test_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_test_test_proto_goTypes,
		DependencyIndexes: file_api_test_test_proto_depIdxs,
		MessageInfos:      file_api_test_test_proto_msgTypes,
	}.Build()
	File_api_test_test_proto = out.File
	file_api_test_test_proto_rawDesc = nil
	file_api_test_test_proto_goTypes = nil
	file_api_test_test_proto_depIdxs = nil
}
