// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/event/v1/event_stream.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_OK                  Code = 0
	Code_CANCELLED           Code = 1
	Code_UNKNOWN             Code = 2
	Code_INVALID_ARGUMENT    Code = 3
	Code_DEADLINE_EXCEEDED   Code = 4
	Code_NOT_FOUND           Code = 5
	Code_ALREADY_EXISTS      Code = 6
	Code_PERMISSION_DENIED   Code = 7
	Code_RESOURCE_EXHAUSTED  Code = 8
	Code_FAILED_PRECONDITION Code = 9
	Code_ABORTED             Code = 10
	Code_OUT_OF_RANGE        Code = 11
	Code_UNIMPLEMENTED       Code = 12
	Code_INTERNAL            Code = 13
	Code_UNAVAILABLE         Code = 14
	Code_DATA_LOSS           Code = 15
	Code_UNAUTHENTICATED     Code = 16
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "OK",
		1:  "CANCELLED",
		2:  "UNKNOWN",
		3:  "INVALID_ARGUMENT",
		4:  "DEADLINE_EXCEEDED",
		5:  "NOT_FOUND",
		6:  "ALREADY_EXISTS",
		7:  "PERMISSION_DENIED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "FAILED_PRECONDITION",
		10: "ABORTED",
		11: "OUT_OF_RANGE",
		12: "UNIMPLEMENTED",
		13: "INTERNAL",
		14: "UNAVAILABLE",
		15: "DATA_LOSS",
		16: "UNAUTHENTICATED",
	}
	Code_value = map[string]int32{
		"OK":                  0,
		"CANCELLED":           1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"UNAUTHENTICATED":     16,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_api_event_v1_event_stream_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_api_event_v1_event_stream_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{0}
}

type BeatHeartResponse_Flag int32

const (
	// 送达
	BeatHeartResponse_ACK BeatHeartResponse_Flag = 0
	// sessionId或服务失效, 需要发起online请求
	BeatHeartResponse_FIN BeatHeartResponse_Flag = 1
	// token失效, 需要重新登录
	BeatHeartResponse_RST BeatHeartResponse_Flag = 2
)

// Enum value maps for BeatHeartResponse_Flag.
var (
	BeatHeartResponse_Flag_name = map[int32]string{
		0: "ACK",
		1: "FIN",
		2: "RST",
	}
	BeatHeartResponse_Flag_value = map[string]int32{
		"ACK": 0,
		"FIN": 1,
		"RST": 2,
	}
)

func (x BeatHeartResponse_Flag) Enum() *BeatHeartResponse_Flag {
	p := new(BeatHeartResponse_Flag)
	*p = x
	return p
}

func (x BeatHeartResponse_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeatHeartResponse_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_api_event_v1_event_stream_proto_enumTypes[1].Descriptor()
}

func (BeatHeartResponse_Flag) Type() protoreflect.EnumType {
	return &file_api_event_v1_event_stream_proto_enumTypes[1]
}

func (x BeatHeartResponse_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeatHeartResponse_Flag.Descriptor instead.
func (BeatHeartResponse_Flag) EnumDescriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{6, 0}
}

type EventStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Event:
	//	*EventStreamRequest_OnlineRequest
	//	*EventStreamRequest_BeatHeartRequest
	//	*EventStreamRequest_OfflineRequest
	Event isEventStreamRequest_Event `protobuf_oneof:"event"`
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{0}
}

func (x *EventStreamRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (m *EventStreamRequest) GetEvent() isEventStreamRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EventStreamRequest) GetOnlineRequest() *OnlineRequest {
	if x, ok := x.GetEvent().(*EventStreamRequest_OnlineRequest); ok {
		return x.OnlineRequest
	}
	return nil
}

func (x *EventStreamRequest) GetBeatHeartRequest() *BeatHeartRequest {
	if x, ok := x.GetEvent().(*EventStreamRequest_BeatHeartRequest); ok {
		return x.BeatHeartRequest
	}
	return nil
}

func (x *EventStreamRequest) GetOfflineRequest() *OfflineRequest {
	if x, ok := x.GetEvent().(*EventStreamRequest_OfflineRequest); ok {
		return x.OfflineRequest
	}
	return nil
}

type isEventStreamRequest_Event interface {
	isEventStreamRequest_Event()
}

type EventStreamRequest_OnlineRequest struct {
	OnlineRequest *OnlineRequest `protobuf:"bytes,2,opt,name=onlineRequest,proto3,oneof"`
}

type EventStreamRequest_BeatHeartRequest struct {
	BeatHeartRequest *BeatHeartRequest `protobuf:"bytes,3,opt,name=beatHeartRequest,proto3,oneof"`
}

type EventStreamRequest_OfflineRequest struct {
	OfflineRequest *OfflineRequest `protobuf:"bytes,4,opt,name=offlineRequest,proto3,oneof"`
}

func (*EventStreamRequest_OnlineRequest) isEventStreamRequest_Event() {}

func (*EventStreamRequest_BeatHeartRequest) isEventStreamRequest_Event() {}

func (*EventStreamRequest_OfflineRequest) isEventStreamRequest_Event() {}

type EventStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code     Code   `protobuf:"varint,2,opt,name=code,proto3,enum=gateway.api.event.v1.Code" json:"code,omitempty"`
	Messages string `protobuf:"bytes,3,opt,name=messages,proto3" json:"messages,omitempty"`
	// Types that are assignable to Event:
	//	*EventStreamResponse_OnlineResponse
	//	*EventStreamResponse_BeatHeartResponse
	//	*EventStreamResponse_OfflineResponse
	Event isEventStreamResponse_Event `protobuf_oneof:"event"`
}

func (x *EventStreamResponse) Reset() {
	*x = EventStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamResponse) ProtoMessage() {}

func (x *EventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamResponse.ProtoReflect.Descriptor instead.
func (*EventStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{1}
}

func (x *EventStreamResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EventStreamResponse) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_OK
}

func (x *EventStreamResponse) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

func (m *EventStreamResponse) GetEvent() isEventStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EventStreamResponse) GetOnlineResponse() *OnlineResponse {
	if x, ok := x.GetEvent().(*EventStreamResponse_OnlineResponse); ok {
		return x.OnlineResponse
	}
	return nil
}

func (x *EventStreamResponse) GetBeatHeartResponse() *BeatHeartResponse {
	if x, ok := x.GetEvent().(*EventStreamResponse_BeatHeartResponse); ok {
		return x.BeatHeartResponse
	}
	return nil
}

func (x *EventStreamResponse) GetOfflineResponse() *OfflineResponse {
	if x, ok := x.GetEvent().(*EventStreamResponse_OfflineResponse); ok {
		return x.OfflineResponse
	}
	return nil
}

type isEventStreamResponse_Event interface {
	isEventStreamResponse_Event()
}

type EventStreamResponse_OnlineResponse struct {
	OnlineResponse *OnlineResponse `protobuf:"bytes,4,opt,name=onlineResponse,proto3,oneof"`
}

type EventStreamResponse_BeatHeartResponse struct {
	BeatHeartResponse *BeatHeartResponse `protobuf:"bytes,5,opt,name=beatHeartResponse,proto3,oneof"`
}

type EventStreamResponse_OfflineResponse struct {
	OfflineResponse *OfflineResponse `protobuf:"bytes,6,opt,name=offlineResponse,proto3,oneof"`
}

func (*EventStreamResponse_OnlineResponse) isEventStreamResponse_Event() {}

func (*EventStreamResponse_BeatHeartResponse) isEventStreamResponse_Event() {}

func (*EventStreamResponse_OfflineResponse) isEventStreamResponse_Event() {}

// 登录后上线request
type OnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *OnlineRequest) Reset() {
	*x = OnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRequest) ProtoMessage() {}

func (x *OnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRequest.ProtoReflect.Descriptor instead.
func (*OnlineRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 心跳request
type BeatHeartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *BeatHeartRequest) Reset() {
	*x = BeatHeartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeatHeartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatHeartRequest) ProtoMessage() {}

func (x *BeatHeartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatHeartRequest.ProtoReflect.Descriptor instead.
func (*BeatHeartRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{3}
}

func (x *BeatHeartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 下线request
type OfflineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *OfflineRequest) Reset() {
	*x = OfflineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineRequest) ProtoMessage() {}

func (x *OfflineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineRequest.ProtoReflect.Descriptor instead.
func (*OfflineRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{4}
}

func (x *OfflineRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OfflineRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 登录后上线response
type OnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *OnlineResponse) Reset() {
	*x = OnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineResponse) ProtoMessage() {}

func (x *OnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineResponse.ProtoReflect.Descriptor instead.
func (*OnlineResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{5}
}

func (x *OnlineResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 心跳response
type BeatHeartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag BeatHeartResponse_Flag `protobuf:"varint,1,opt,name=flag,proto3,enum=gateway.api.event.v1.BeatHeartResponse_Flag" json:"flag,omitempty"`
}

func (x *BeatHeartResponse) Reset() {
	*x = BeatHeartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeatHeartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatHeartResponse) ProtoMessage() {}

func (x *BeatHeartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatHeartResponse.ProtoReflect.Descriptor instead.
func (*BeatHeartResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{6}
}

func (x *BeatHeartResponse) GetFlag() BeatHeartResponse_Flag {
	if x != nil {
		return x.Flag
	}
	return BeatHeartResponse_ACK
}

// 下线response
type OfflineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *OfflineResponse) Reset() {
	*x = OfflineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineResponse) ProtoMessage() {}

func (x *OfflineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineResponse.ProtoReflect.Descriptor instead.
func (*OfflineResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{7}
}

func (x *OfflineResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_event_v1_event_stream_proto protoreflect.FileDescriptor

var file_api_event_v1_event_stream_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x22, 0xa6, 0x02, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x4b, 0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x54, 0x0a, 0x10, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x0e, 0x6f, 0x66, 0x66, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0xfc, 0x02, 0x0a, 0x13, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x4e, 0x0a, 0x0e, 0x6f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x11, 0x62, 0x65,
	0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61,
	0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x11, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x25, 0x0a, 0x0d, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x10, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0e, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x2e,
	0x0a, 0x0e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x78,
	0x0a, 0x11, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2c, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x21, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x07, 0x0a,
	0x03, 0x41, 0x43, 0x4b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x49, 0x4e, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x52, 0x53, 0x54, 0x10, 0x02, 0x22, 0x27, 0x0a, 0x0f, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x2a, 0xb7, 0x02, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x14,
	0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45,
	0x4e, 0x54, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x45, 0x41, 0x44, 0x4c, 0x49, 0x4e, 0x45,
	0x5f, 0x45, 0x58, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4e,
	0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4c,
	0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x06, 0x12, 0x15,
	0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e,
	0x49, 0x45, 0x44, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x5f, 0x45, 0x58, 0x48, 0x41, 0x55, 0x53, 0x54, 0x45, 0x44, 0x10, 0x08, 0x12, 0x17, 0x0a,
	0x13, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x49,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45,
	0x44, 0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x52, 0x41,
	0x4e, 0x47, 0x45, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x49, 0x4d, 0x50, 0x4c, 0x45,
	0x4d, 0x45, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x0c, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45,
	0x52, 0x4e, 0x41, 0x4c, 0x10, 0x0d, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49,
	0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x0e, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x41, 0x54, 0x41, 0x5f,
	0x4c, 0x4f, 0x53, 0x53, 0x10, 0x0f, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48,
	0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x10, 0x32, 0x77, 0x0a, 0x0b, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x68, 0x0a, 0x0b, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x28, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x29, 0x0a, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x17, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_event_v1_event_stream_proto_rawDescOnce sync.Once
	file_api_event_v1_event_stream_proto_rawDescData = file_api_event_v1_event_stream_proto_rawDesc
)

func file_api_event_v1_event_stream_proto_rawDescGZIP() []byte {
	file_api_event_v1_event_stream_proto_rawDescOnce.Do(func() {
		file_api_event_v1_event_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_event_v1_event_stream_proto_rawDescData)
	})
	return file_api_event_v1_event_stream_proto_rawDescData
}

var file_api_event_v1_event_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_event_v1_event_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_event_v1_event_stream_proto_goTypes = []interface{}{
	(Code)(0),                   // 0: gateway.api.event.v1.Code
	(BeatHeartResponse_Flag)(0), // 1: gateway.api.event.v1.BeatHeartResponse.Flag
	(*EventStreamRequest)(nil),  // 2: gateway.api.event.v1.EventStreamRequest
	(*EventStreamResponse)(nil), // 3: gateway.api.event.v1.EventStreamResponse
	(*OnlineRequest)(nil),       // 4: gateway.api.event.v1.OnlineRequest
	(*BeatHeartRequest)(nil),    // 5: gateway.api.event.v1.BeatHeartRequest
	(*OfflineRequest)(nil),      // 6: gateway.api.event.v1.OfflineRequest
	(*OnlineResponse)(nil),      // 7: gateway.api.event.v1.OnlineResponse
	(*BeatHeartResponse)(nil),   // 8: gateway.api.event.v1.BeatHeartResponse
	(*OfflineResponse)(nil),     // 9: gateway.api.event.v1.OfflineResponse
}
var file_api_event_v1_event_stream_proto_depIdxs = []int32{
	4, // 0: gateway.api.event.v1.EventStreamRequest.onlineRequest:type_name -> gateway.api.event.v1.OnlineRequest
	5, // 1: gateway.api.event.v1.EventStreamRequest.beatHeartRequest:type_name -> gateway.api.event.v1.BeatHeartRequest
	6, // 2: gateway.api.event.v1.EventStreamRequest.offlineRequest:type_name -> gateway.api.event.v1.OfflineRequest
	0, // 3: gateway.api.event.v1.EventStreamResponse.code:type_name -> gateway.api.event.v1.Code
	7, // 4: gateway.api.event.v1.EventStreamResponse.onlineResponse:type_name -> gateway.api.event.v1.OnlineResponse
	8, // 5: gateway.api.event.v1.EventStreamResponse.beatHeartResponse:type_name -> gateway.api.event.v1.BeatHeartResponse
	9, // 6: gateway.api.event.v1.EventStreamResponse.offlineResponse:type_name -> gateway.api.event.v1.OfflineResponse
	1, // 7: gateway.api.event.v1.BeatHeartResponse.flag:type_name -> gateway.api.event.v1.BeatHeartResponse.Flag
	2, // 8: gateway.api.event.v1.EventStream.EventStream:input_type -> gateway.api.event.v1.EventStreamRequest
	3, // 9: gateway.api.event.v1.EventStream.EventStream:output_type -> gateway.api.event.v1.EventStreamResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_api_event_v1_event_stream_proto_init() }
func file_api_event_v1_event_stream_proto_init() {
	if File_api_event_v1_event_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_event_v1_event_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeatHeartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeatHeartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_event_v1_event_stream_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EventStreamRequest_OnlineRequest)(nil),
		(*EventStreamRequest_BeatHeartRequest)(nil),
		(*EventStreamRequest_OfflineRequest)(nil),
	}
	file_api_event_v1_event_stream_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*EventStreamResponse_OnlineResponse)(nil),
		(*EventStreamResponse_BeatHeartResponse)(nil),
		(*EventStreamResponse_OfflineResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_event_v1_event_stream_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_event_v1_event_stream_proto_goTypes,
		DependencyIndexes: file_api_event_v1_event_stream_proto_depIdxs,
		EnumInfos:         file_api_event_v1_event_stream_proto_enumTypes,
		MessageInfos:      file_api_event_v1_event_stream_proto_msgTypes,
	}.Build()
	File_api_event_v1_event_stream_proto = out.File
	file_api_event_v1_event_stream_proto_rawDesc = nil
	file_api_event_v1_event_stream_proto_goTypes = nil
	file_api_event_v1_event_stream_proto_depIdxs = nil
}
