// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: api/event/v1/event_stream.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeatHeartResponse_Flag int32

const (
	// 送达
	BeatHeartResponse_ACK BeatHeartResponse_Flag = 0
	// sessionId或服务失效, 需要发起online请求
	BeatHeartResponse_FIN BeatHeartResponse_Flag = 1
	// token失效, 需要重新登录
	BeatHeartResponse_RST BeatHeartResponse_Flag = 2
)

// Enum value maps for BeatHeartResponse_Flag.
var (
	BeatHeartResponse_Flag_name = map[int32]string{
		0: "ACK",
		1: "FIN",
		2: "RST",
	}
	BeatHeartResponse_Flag_value = map[string]int32{
		"ACK": 0,
		"FIN": 1,
		"RST": 2,
	}
)

func (x BeatHeartResponse_Flag) Enum() *BeatHeartResponse_Flag {
	p := new(BeatHeartResponse_Flag)
	*p = x
	return p
}

func (x BeatHeartResponse_Flag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeatHeartResponse_Flag) Descriptor() protoreflect.EnumDescriptor {
	return file_api_event_v1_event_stream_proto_enumTypes[0].Descriptor()
}

func (BeatHeartResponse_Flag) Type() protoreflect.EnumType {
	return &file_api_event_v1_event_stream_proto_enumTypes[0]
}

func (x BeatHeartResponse_Flag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeatHeartResponse_Flag.Descriptor instead.
func (BeatHeartResponse_Flag) EnumDescriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{5, 0}
}

type EventStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Event:
	//	*EventStreamRequest_OnlineRequest
	//	*EventStreamRequest_BeatHeartRequest
	Event isEventStreamRequest_Event `protobuf_oneof:"event"`
}

func (x *EventStreamRequest) Reset() {
	*x = EventStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamRequest) ProtoMessage() {}

func (x *EventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamRequest.ProtoReflect.Descriptor instead.
func (*EventStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{0}
}

func (x *EventStreamRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (m *EventStreamRequest) GetEvent() isEventStreamRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EventStreamRequest) GetOnlineRequest() *OnlineRequest {
	if x, ok := x.GetEvent().(*EventStreamRequest_OnlineRequest); ok {
		return x.OnlineRequest
	}
	return nil
}

func (x *EventStreamRequest) GetBeatHeartRequest() *BeatHeartRequest {
	if x, ok := x.GetEvent().(*EventStreamRequest_BeatHeartRequest); ok {
		return x.BeatHeartRequest
	}
	return nil
}

type isEventStreamRequest_Event interface {
	isEventStreamRequest_Event()
}

type EventStreamRequest_OnlineRequest struct {
	OnlineRequest *OnlineRequest `protobuf:"bytes,2,opt,name=onlineRequest,proto3,oneof"`
}

type EventStreamRequest_BeatHeartRequest struct {
	BeatHeartRequest *BeatHeartRequest `protobuf:"bytes,3,opt,name=beatHeartRequest,proto3,oneof"`
}

func (*EventStreamRequest_OnlineRequest) isEventStreamRequest_Event() {}

func (*EventStreamRequest_BeatHeartRequest) isEventStreamRequest_Event() {}

type EventStreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Types that are assignable to Event:
	//	*EventStreamResponse_OnlineResponse
	//	*EventStreamResponse_BeatHeartResponse
	Event isEventStreamResponse_Event `protobuf_oneof:"event"`
}

func (x *EventStreamResponse) Reset() {
	*x = EventStreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamResponse) ProtoMessage() {}

func (x *EventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamResponse.ProtoReflect.Descriptor instead.
func (*EventStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{1}
}

func (x *EventStreamResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (m *EventStreamResponse) GetEvent() isEventStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *EventStreamResponse) GetOnlineResponse() *OnlineResponse {
	if x, ok := x.GetEvent().(*EventStreamResponse_OnlineResponse); ok {
		return x.OnlineResponse
	}
	return nil
}

func (x *EventStreamResponse) GetBeatHeartResponse() *BeatHeartResponse {
	if x, ok := x.GetEvent().(*EventStreamResponse_BeatHeartResponse); ok {
		return x.BeatHeartResponse
	}
	return nil
}

type isEventStreamResponse_Event interface {
	isEventStreamResponse_Event()
}

type EventStreamResponse_OnlineResponse struct {
	OnlineResponse *OnlineResponse `protobuf:"bytes,2,opt,name=onlineResponse,proto3,oneof"`
}

type EventStreamResponse_BeatHeartResponse struct {
	BeatHeartResponse *BeatHeartResponse `protobuf:"bytes,3,opt,name=beatHeartResponse,proto3,oneof"`
}

func (*EventStreamResponse_OnlineResponse) isEventStreamResponse_Event() {}

func (*EventStreamResponse_BeatHeartResponse) isEventStreamResponse_Event() {}

// ------------------------------
// 以下为客户端发起的request event
type OnlineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *OnlineRequest) Reset() {
	*x = OnlineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineRequest) ProtoMessage() {}

func (x *OnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineRequest.ProtoReflect.Descriptor instead.
func (*OnlineRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type BeatHeartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *BeatHeartRequest) Reset() {
	*x = BeatHeartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeatHeartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatHeartRequest) ProtoMessage() {}

func (x *BeatHeartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatHeartRequest.ProtoReflect.Descriptor instead.
func (*BeatHeartRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{3}
}

func (x *BeatHeartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ------------------------------
// 以下为服务端发起的request event
type OnlineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *OnlineResponse) Reset() {
	*x = OnlineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineResponse) ProtoMessage() {}

func (x *OnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineResponse.ProtoReflect.Descriptor instead.
func (*OnlineResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type BeatHeartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag BeatHeartResponse_Flag `protobuf:"varint,1,opt,name=flag,proto3,enum=gateway.api.event.v1.BeatHeartResponse_Flag" json:"flag,omitempty"`
}

func (x *BeatHeartResponse) Reset() {
	*x = BeatHeartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_event_v1_event_stream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeatHeartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeatHeartResponse) ProtoMessage() {}

func (x *BeatHeartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_stream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeatHeartResponse.ProtoReflect.Descriptor instead.
func (*BeatHeartResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_stream_proto_rawDescGZIP(), []int{5}
}

func (x *BeatHeartResponse) GetFlag() BeatHeartResponse_Flag {
	if x != nil {
		return x.Flag
	}
	return BeatHeartResponse_ACK
}

var File_api_event_v1_event_stream_proto protoreflect.FileDescriptor

var file_api_event_v1_event_stream_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x14, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x22, 0xd6, 0x01, 0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x4b, 0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0d, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x54, 0x0a, 0x10, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0xdd, 0x01, 0x0a, 0x13, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x4e,
	0x0a, 0x0e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57,
	0x0a, 0x11, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x62, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x25, 0x0a, 0x0d, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x30, 0x0a, 0x10, 0x42, 0x65, 0x61, 0x74, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x0e, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x11, 0x42, 0x65, 0x61,
	0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x65, 0x61, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x6c, 0x61, 0x67, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67,
	0x22, 0x21, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x46, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x53,
	0x54, 0x10, 0x02, 0x32, 0x77, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x12, 0x68, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x28, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x29, 0x0a, 0x0c,
	0x61, 0x70, 0x69, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x17,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_event_v1_event_stream_proto_rawDescOnce sync.Once
	file_api_event_v1_event_stream_proto_rawDescData = file_api_event_v1_event_stream_proto_rawDesc
)

func file_api_event_v1_event_stream_proto_rawDescGZIP() []byte {
	file_api_event_v1_event_stream_proto_rawDescOnce.Do(func() {
		file_api_event_v1_event_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_event_v1_event_stream_proto_rawDescData)
	})
	return file_api_event_v1_event_stream_proto_rawDescData
}

var file_api_event_v1_event_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_event_v1_event_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_event_v1_event_stream_proto_goTypes = []interface{}{
	(BeatHeartResponse_Flag)(0), // 0: gateway.api.event.v1.BeatHeartResponse.Flag
	(*EventStreamRequest)(nil),  // 1: gateway.api.event.v1.EventStreamRequest
	(*EventStreamResponse)(nil), // 2: gateway.api.event.v1.EventStreamResponse
	(*OnlineRequest)(nil),       // 3: gateway.api.event.v1.OnlineRequest
	(*BeatHeartRequest)(nil),    // 4: gateway.api.event.v1.BeatHeartRequest
	(*OnlineResponse)(nil),      // 5: gateway.api.event.v1.OnlineResponse
	(*BeatHeartResponse)(nil),   // 6: gateway.api.event.v1.BeatHeartResponse
}
var file_api_event_v1_event_stream_proto_depIdxs = []int32{
	3, // 0: gateway.api.event.v1.EventStreamRequest.onlineRequest:type_name -> gateway.api.event.v1.OnlineRequest
	4, // 1: gateway.api.event.v1.EventStreamRequest.beatHeartRequest:type_name -> gateway.api.event.v1.BeatHeartRequest
	5, // 2: gateway.api.event.v1.EventStreamResponse.onlineResponse:type_name -> gateway.api.event.v1.OnlineResponse
	6, // 3: gateway.api.event.v1.EventStreamResponse.beatHeartResponse:type_name -> gateway.api.event.v1.BeatHeartResponse
	0, // 4: gateway.api.event.v1.BeatHeartResponse.flag:type_name -> gateway.api.event.v1.BeatHeartResponse.Flag
	1, // 5: gateway.api.event.v1.EventStream.EventStream:input_type -> gateway.api.event.v1.EventStreamRequest
	2, // 6: gateway.api.event.v1.EventStream.EventStream:output_type -> gateway.api.event.v1.EventStreamResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_event_v1_event_stream_proto_init() }
func file_api_event_v1_event_stream_proto_init() {
	if File_api_event_v1_event_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_event_v1_event_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeatHeartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_event_v1_event_stream_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeatHeartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_event_v1_event_stream_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EventStreamRequest_OnlineRequest)(nil),
		(*EventStreamRequest_BeatHeartRequest)(nil),
	}
	file_api_event_v1_event_stream_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*EventStreamResponse_OnlineResponse)(nil),
		(*EventStreamResponse_BeatHeartResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_event_v1_event_stream_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_event_v1_event_stream_proto_goTypes,
		DependencyIndexes: file_api_event_v1_event_stream_proto_depIdxs,
		EnumInfos:         file_api_event_v1_event_stream_proto_enumTypes,
		MessageInfos:      file_api_event_v1_event_stream_proto_msgTypes,
	}.Build()
	File_api_event_v1_event_stream_proto = out.File
	file_api_event_v1_event_stream_proto_rawDesc = nil
	file_api_event_v1_event_stream_proto_goTypes = nil
	file_api_event_v1_event_stream_proto_depIdxs = nil
}
