server:
  http:
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9090
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    db: 1
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbitmq:
    addr: 127.0.0.1:5672/
    user: piggytalk-backend
    password: impiggy

project:
  mode: dev