server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/piggytalk?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  rabbitmq:
    addr: 127.0.0.1:5672/
    user: piggytalk-backend
    password: impiggy
