server:
  http:
    addr: 0.0.0.0:8002
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/piggytalk?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
  rabbitmq:
    addr: 127.0.0.1:5672/
    user: piggytalk-backend
    password: impiggy
  redis:
    addr: 127.0.0.1:6379
    db: 1
    read_timeout: 0.2s
    write_timeout: 0.2s