version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=piggytalk-backend
      - RABBITMQ_DEFAULT_PASS=impiggy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    networks:
      - piggytalk-backend-bridge

networks:
  piggytalk-backend-bridge:
    external:
      name: piggytalk-backend-bridge