// Code generated by entc, DO NOT EDIT.

package userinfo

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the userinfo type in the database.
	Label = "user_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldGmtCreate holds the string denoting the gmt_create field in the database.
	FieldGmtCreate = "gmt_create"
	// FieldGmtModified holds the string denoting the gmt_modified field in the database.
	FieldGmtModified = "gmt_modified"
	// FieldNickname holds the string denoting the nickname field in the database.
	FieldNickname = "nickname"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// Table holds the table name of the userinfo in the database.
	Table = "user_infos"
)

// Columns holds all SQL columns for userinfo fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldGmtCreate,
	FieldGmtModified,
	FieldNickname,
	FieldAvatar,
	FieldEmail,
	FieldPhone,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID func() uuid.UUID
	// DefaultGmtCreate holds the default value on creation for the "gmt_create" field.
	DefaultGmtCreate func() time.Time
	// DefaultGmtModified holds the default value on creation for the "gmt_modified" field.
	DefaultGmtModified func() time.Time
	// NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	NicknameValidator func(string) error
	// DefaultAvatar holds the default value on creation for the "avatar" field.
	DefaultAvatar string
)
