// Code generated by entc, DO NOT EDIT.

package ent

import (
	"account/ent/userinfo"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserInfoCreate is the builder for creating a UserInfo entity.
type UserInfoCreate struct {
	config
	mutation *UserInfoMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (uic *UserInfoCreate) SetUUID(u uuid.UUID) *UserInfoCreate {
	uic.mutation.SetUUID(u)
	return uic
}

// SetGmtCreate sets the "gmt_create" field.
func (uic *UserInfoCreate) SetGmtCreate(t time.Time) *UserInfoCreate {
	uic.mutation.SetGmtCreate(t)
	return uic
}

// SetNillableGmtCreate sets the "gmt_create" field if the given value is not nil.
func (uic *UserInfoCreate) SetNillableGmtCreate(t *time.Time) *UserInfoCreate {
	if t != nil {
		uic.SetGmtCreate(*t)
	}
	return uic
}

// SetGmtModified sets the "gmt_modified" field.
func (uic *UserInfoCreate) SetGmtModified(t time.Time) *UserInfoCreate {
	uic.mutation.SetGmtModified(t)
	return uic
}

// SetNillableGmtModified sets the "gmt_modified" field if the given value is not nil.
func (uic *UserInfoCreate) SetNillableGmtModified(t *time.Time) *UserInfoCreate {
	if t != nil {
		uic.SetGmtModified(*t)
	}
	return uic
}

// SetNickname sets the "nickname" field.
func (uic *UserInfoCreate) SetNickname(s string) *UserInfoCreate {
	uic.mutation.SetNickname(s)
	return uic
}

// SetAvatar sets the "avatar" field.
func (uic *UserInfoCreate) SetAvatar(s string) *UserInfoCreate {
	uic.mutation.SetAvatar(s)
	return uic
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uic *UserInfoCreate) SetNillableAvatar(s *string) *UserInfoCreate {
	if s != nil {
		uic.SetAvatar(*s)
	}
	return uic
}

// SetEmail sets the "email" field.
func (uic *UserInfoCreate) SetEmail(s string) *UserInfoCreate {
	uic.mutation.SetEmail(s)
	return uic
}

// SetPhone sets the "phone" field.
func (uic *UserInfoCreate) SetPhone(s string) *UserInfoCreate {
	uic.mutation.SetPhone(s)
	return uic
}

// Mutation returns the UserInfoMutation object of the builder.
func (uic *UserInfoCreate) Mutation() *UserInfoMutation {
	return uic.mutation
}

// Save creates the UserInfo in the database.
func (uic *UserInfoCreate) Save(ctx context.Context) (*UserInfo, error) {
	var (
		err  error
		node *UserInfo
	)
	uic.defaults()
	if len(uic.hooks) == 0 {
		if err = uic.check(); err != nil {
			return nil, err
		}
		node, err = uic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = uic.check(); err != nil {
				return nil, err
			}
			uic.mutation = mutation
			if node, err = uic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(uic.hooks) - 1; i >= 0; i-- {
			if uic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = uic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uic *UserInfoCreate) SaveX(ctx context.Context) *UserInfo {
	v, err := uic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uic *UserInfoCreate) Exec(ctx context.Context) error {
	_, err := uic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uic *UserInfoCreate) ExecX(ctx context.Context) {
	if err := uic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uic *UserInfoCreate) defaults() {
	if _, ok := uic.mutation.UUID(); !ok {
		v := userinfo.DefaultUUID()
		uic.mutation.SetUUID(v)
	}
	if _, ok := uic.mutation.GmtCreate(); !ok {
		v := userinfo.DefaultGmtCreate()
		uic.mutation.SetGmtCreate(v)
	}
	if _, ok := uic.mutation.GmtModified(); !ok {
		v := userinfo.DefaultGmtModified()
		uic.mutation.SetGmtModified(v)
	}
	if _, ok := uic.mutation.Avatar(); !ok {
		v := userinfo.DefaultAvatar
		uic.mutation.SetAvatar(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uic *UserInfoCreate) check() error {
	if _, ok := uic.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "uuid"`)}
	}
	if _, ok := uic.mutation.GmtCreate(); !ok {
		return &ValidationError{Name: "gmt_create", err: errors.New(`ent: missing required field "gmt_create"`)}
	}
	if _, ok := uic.mutation.GmtModified(); !ok {
		return &ValidationError{Name: "gmt_modified", err: errors.New(`ent: missing required field "gmt_modified"`)}
	}
	if _, ok := uic.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "nickname"`)}
	}
	if v, ok := uic.mutation.Nickname(); ok {
		if err := userinfo.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "nickname": %w`, err)}
		}
	}
	if _, ok := uic.mutation.Avatar(); !ok {
		return &ValidationError{Name: "avatar", err: errors.New(`ent: missing required field "avatar"`)}
	}
	if _, ok := uic.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "email"`)}
	}
	if _, ok := uic.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "phone"`)}
	}
	return nil
}

func (uic *UserInfoCreate) sqlSave(ctx context.Context) (*UserInfo, error) {
	_node, _spec := uic.createSpec()
	if err := sqlgraph.CreateNode(ctx, uic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (uic *UserInfoCreate) createSpec() (*UserInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &UserInfo{config: uic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: userinfo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userinfo.FieldID,
			},
		}
	)
	if value, ok := uic.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: userinfo.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := uic.mutation.GmtCreate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userinfo.FieldGmtCreate,
		})
		_node.GmtCreate = value
	}
	if value, ok := uic.mutation.GmtModified(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: userinfo.FieldGmtModified,
		})
		_node.GmtModified = value
	}
	if value, ok := uic.mutation.Nickname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userinfo.FieldNickname,
		})
		_node.Nickname = value
	}
	if value, ok := uic.mutation.Avatar(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userinfo.FieldAvatar,
		})
		_node.Avatar = value
	}
	if value, ok := uic.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userinfo.FieldEmail,
		})
		_node.Email = value
	}
	if value, ok := uic.mutation.Phone(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: userinfo.FieldPhone,
		})
		_node.Phone = value
	}
	return _node, _spec
}

// UserInfoCreateBulk is the builder for creating many UserInfo entities in bulk.
type UserInfoCreateBulk struct {
	config
	builders []*UserInfoCreate
}

// Save creates the UserInfo entities in the database.
func (uicb *UserInfoCreateBulk) Save(ctx context.Context) ([]*UserInfo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(uicb.builders))
	nodes := make([]*UserInfo, len(uicb.builders))
	mutators := make([]Mutator, len(uicb.builders))
	for i := range uicb.builders {
		func(i int, root context.Context) {
			builder := uicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, uicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, uicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, uicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (uicb *UserInfoCreateBulk) SaveX(ctx context.Context) []*UserInfo {
	v, err := uicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uicb *UserInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := uicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uicb *UserInfoCreateBulk) ExecX(ctx context.Context) {
	if err := uicb.Exec(ctx); err != nil {
		panic(err)
	}
}
