// Code generated by entc, DO NOT EDIT.

package ent

import (
	"account/ent/userinfo"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UserInfo is the model entity for the UserInfo schema.
type UserInfo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID uuid.UUID `json:"uuid,omitempty"`
	// GmtCreate holds the value of the "gmt_create" field.
	GmtCreate time.Time `json:"gmt_create,omitempty"`
	// GmtModified holds the value of the "gmt_modified" field.
	GmtModified time.Time `json:"gmt_modified,omitempty"`
	// Nickname holds the value of the "nickname" field.
	Nickname string `json:"nickname,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar string `json:"avatar,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserInfo) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case userinfo.FieldID:
			values[i] = new(sql.NullInt64)
		case userinfo.FieldNickname, userinfo.FieldAvatar, userinfo.FieldEmail, userinfo.FieldPhone:
			values[i] = new(sql.NullString)
		case userinfo.FieldGmtCreate, userinfo.FieldGmtModified:
			values[i] = new(sql.NullTime)
		case userinfo.FieldUUID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserInfo", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserInfo fields.
func (ui *UserInfo) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userinfo.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ui.ID = int(value.Int64)
		case userinfo.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value != nil {
				ui.UUID = *value
			}
		case userinfo.FieldGmtCreate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field gmt_create", values[i])
			} else if value.Valid {
				ui.GmtCreate = value.Time
			}
		case userinfo.FieldGmtModified:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field gmt_modified", values[i])
			} else if value.Valid {
				ui.GmtModified = value.Time
			}
		case userinfo.FieldNickname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nickname", values[i])
			} else if value.Valid {
				ui.Nickname = value.String
			}
		case userinfo.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				ui.Avatar = value.String
			}
		case userinfo.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				ui.Email = value.String
			}
		case userinfo.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				ui.Phone = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this UserInfo.
// Note that you need to call UserInfo.Unwrap() before calling this method if this UserInfo
// was returned from a transaction, and the transaction was committed or rolled back.
func (ui *UserInfo) Update() *UserInfoUpdateOne {
	return (&UserInfoClient{config: ui.config}).UpdateOne(ui)
}

// Unwrap unwraps the UserInfo entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ui *UserInfo) Unwrap() *UserInfo {
	tx, ok := ui.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserInfo is not a transactional entity")
	}
	ui.config.driver = tx.drv
	return ui
}

// String implements the fmt.Stringer.
func (ui *UserInfo) String() string {
	var builder strings.Builder
	builder.WriteString("UserInfo(")
	builder.WriteString(fmt.Sprintf("id=%v", ui.ID))
	builder.WriteString(", uuid=")
	builder.WriteString(fmt.Sprintf("%v", ui.UUID))
	builder.WriteString(", gmt_create=")
	builder.WriteString(ui.GmtCreate.Format(time.ANSIC))
	builder.WriteString(", gmt_modified=")
	builder.WriteString(ui.GmtModified.Format(time.ANSIC))
	builder.WriteString(", nickname=")
	builder.WriteString(ui.Nickname)
	builder.WriteString(", avatar=")
	builder.WriteString(ui.Avatar)
	builder.WriteString(", email=")
	builder.WriteString(ui.Email)
	builder.WriteString(", phone=")
	builder.WriteString(ui.Phone)
	builder.WriteByte(')')
	return builder.String()
}

// UserInfos is a parsable slice of UserInfo.
type UserInfos []*UserInfo

func (ui UserInfos) config(cfg config) {
	for _i := range ui {
		ui[_i].config = cfg
	}
}
